name: dynVis
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - expat=2.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.12.1
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
#      - git+https://gitlab.inria.fr/apister/bipdyngraph
      - ../bipDynGraph
      - angelcommunity==2.0.0
      - beautifulsoup4==4.12.3
      - bimlpa==0.1.2
      - blinker==1.7.0
      - cachelib==0.10.2
      - cdlib==0.3.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - decorator==5.1.1
      - demon==2.0.6
      - dynetx==0.3.2
      - eva-lcd==0.1.1
      - flask==3.0.2
      - flask-cors==4.0.0
      - flask-session==0.6.0
      - fonttools==4.47.2
      - future==0.18.3
      - idna==3.6
      - igraph==0.11.3
      - itsdangerous==2.1.2
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonpickle==3.0.2
      - kiwisolver==1.4.5
      - levenshtein==0.24.0
      - markov-clustering==0.0.6.dev0
      - markupsafe==2.1.5
      - matplotlib==3.8.2
      - networkx==3.2.1
      - nf1==0.0.4
      - numpy==1.26.3
      - packaging==23.2
      - pandas==2.2.0
      - pillow==10.2.0
      - platformdirs==4.2.0
      - pooch==1.8.0
      - pulp==2.8.0
      - pydot==2.0.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-igraph==0.11.3
      - python-levenshtein==0.24.0
      - python-louvain==0.16
      - pytz==2024.1
      - rapidfuzz==3.6.1
      - requests==2.31.0
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - seaborn==0.13.2
      - six==1.16.0
      - soupsieve==2.5
      - texttable==1.7.0
      - threadpoolctl==3.2.0
      - thresholdclustering==1.1
      - tqdm==4.66.1
      - tzdata==2023.4
      - urllib3==2.2.0
      - werkzeug==3.0.1
